# Generated by Django 4.2.15 on 2024-08-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cuisine_type',
            field=models.CharField(help_text='Enter the type of cuisine', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='menu_items',
            field=models.TextField(help_text='Enter the menu items', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(help_text='Enter the opening hours', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(help_text='Enter the phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(help_text='Enter the website URL', null=True),
        ),
    ]
