# Generated by Django 4.2.15 on 2024-08-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_place_cuisine_type_place_menu_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='place',
            name='closing_time',
            field=models.TimeField(help_text='Enter the closing time', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_time',
            field=models.TimeField(help_text='Enter the opening time', null=True),
        ),
    ]
