# Generated by Django 4.2.15 on 2024-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_place_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photo',
        ),
        migrations.AddField(
            model_name='place',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Enter the photo URL', null=True),
        ),
    ]
