# Generated by Django 4.2.15 on 2024-08-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_place_photo_place_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Enter the photo URL', max_length=500, null=True),
        ),
    ]
