# Generated by Django 4.2.15 on 2024-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_tag_tagmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='food.tag'),
        ),
    ]
