# Generated by Django 4.2.16 on 2024-09-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_place_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tagmanagement',
            options={'ordering': ['place']},
        ),
    ]
