# Generated by Django 4.2.16 on 2024-09-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_place_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Rstyle',
        ),
    ]
