# Generated by Django 4.2.16 on 2024-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_tag_rstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Enter the name of the store', max_length=20),
        ),
    ]
