# Generated by Django 4.2.16 on 2024-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_place_view_count_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Enter the name of store', max_length=20),
        ),
    ]
