# Generated by Django 4.2.16 on 2024-09-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
