# Generated by Django 4.2.16 on 2024-09-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_homepageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the homepage was viewed'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='Enter the store address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Enter the name of the store', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='food.tag'),
        ),
        migrations.AlterField(
            model_name='place',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Enter the number of views'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Enter the tag name', max_length=10),
        ),
        migrations.AlterField(
            model_name='tagmanagement',
            name='place',
            field=models.ForeignKey(help_text='Select a place for this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.place'),
        ),
        migrations.AlterField(
            model_name='tagmanagement',
            name='tag',
            field=models.ForeignKey(help_text='Select a tag for this place', null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.tag'),
        ),
    ]
